anketler/urls.py
from importlib.resources import path
from django.urls import path
from . import views 


app_name = 'anketler'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.AyrintiView.as_view(), name='ayrinti'),
    path('<int:pk>/sonuclar/', views.SonuclarView.as_view(), name='sonuclar'),
    path('<int:soru_id>/oy/', views.oy, name='oy'),
]

benimsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('anketler/', include('anketler.urls')),
]

anketler/models.py
from django.db import models
import datetime
from django.utils import timezone

class Soru(models.Model):
    soru_metni = models.CharField(max_length=200)
    yayim_tarihi = models.DateTimeField('yayınlanma tarihi')
    def __str__(self):
          return self.soru_metni

    def was_published_recently(self):
        return self.yayim_tarihi >= timezone.now() - datetime.timedelta(days=1)      


class Secim(models.Model):
    soru = models.ForeignKey(Soru, on_delete=models.CASCADE)
    secim_metni = models.CharField(max_length=200)
    oylar = models.IntegerField(default=0)
    def __str__(self):
          return self.secim_metni
  

  

anketler/views.py
from http.client import HTTPResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .common import insert_soru,select_soru,update_soru
from datetime import datetime
from .models import Soru,Secim
from django.http import Http404
from django.template import loader
from django.urls import reverse
from django.views import generic




def index(request):
    son_sorular_listesi = Soru.objects.order_by('-yayim_tarihi')[:5]
    template = loader.get_template('index.html')
    cikti = {
        'son_sorular_listesi': son_sorular_listesi,
    }
    return HttpResponse(template.render(cikti, request))

# class IndexView(generic.ListView):
#     tema_adi = 'anketler/index.html'
#     baglam_nesnesinin_adi = 'son_sorular_listesi'

#     def get_queryset(self):
#         """En son yayınlanan 5 soruyu getir."""
#         return Soru.objects.order_by('-yayim_tarihi')[:5]


class AyrintiView(generic.DetailView):
    model = Soru
    tema_adi = 'anketler/ayrinti.html'


class SonuclarView(generic.DetailView):
    model = Soru
    tema_adi = 'anketler/sonuclar.html'

def oy(request, soru_id):
    soru = get_object_or_404(Soru, pk=soru_id)
    try:
        secim_secildi = soru.secim_set.get(pk=request.POST['secim'])
    except (KeyError, Secim.DoesNotExist):
          # Soruyu oylama biçimini yeniden görüntüleme.
        return render(request, 'anketler/ayrinti.html', {
            'soru': soru,
            'hata_mesaji': "Herhangi bir seçim yapmadınız.",
        })
    else:
        secim_secildi.oylar += 1
        secim_secildi.save()
        # POST verileri her zmaan bir HttpResponseRedirect döndürür. Bu, bir kullanıcı "geri" düğmesine basarsa verilerin iki kez gönderilmesini önler.
        return HttpResponseRedirect(reverse('anketler:sonuclar', args=(soru.id,)))
          

# def index(request):
#     son_sorular_listesi = Soru.objects.order_by('-yayim_tarihi')[:5]
#     cikti = {'son_sorular_listesi': son_sorular_listesi}
#     return render(request, 'anketler/index.html', cikti)

# def ayrinti(request, soru_id):
#     soru = get_object_or_404(Soru, pk=soru_id)
#     return render(request, 'anketler/ayrinti.html', {'soru': soru})       
    


# def sonuclar(request, question_id):
#     soru = get_object_or_404(Soru, pk=question_id)
#     return render(request, 'anketler/sonuclar.html', {'soru': soru})    

anketler/templates/ayrinti.html
  <h1>{{ soru.soru_metni 	}}</h1>

  {% if hata_mesaji %}<p><strong>{{ hata_mesaji 	}}</strong></p>{% endif %}

  <form action="{% url 'anketler:oy' soru.id %}" method="post">
  {% csrf_token %}
  {% for secim in soru.secim_set.all %}
      <input type="radio" name="secim" id="secim{{ forloop.counter 	}}" value="{{ choice.id 	}}" />
      <label for="secim{{ forloop.counter 	}}">{{ secim.secim_metni 	}}</label><br />
  {% endfor %}
  <input type="submit" value="Vote" />
  </form>

anketler/templates/index.html
{% if son_sorular_listesi %}
<ul>
{% for soru in son_sorular_listesi %}
    <li><a href="/anketler/{{ soru.id }}/">{{ soru.soru_metni }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>Anket bulunamadı.</p>
{% endif %}

anketler/templates/sonuclar.html
<h1>{{ soru.soru_metni }}</h1>

<ul>
{% for secim in soru.secim_set.all %}
    <li>{{ secim.secim_metni }} -- {{ secim.oylar }} oy{{ secim.oylar|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'oylar:ayrinti' soru.id %}">Tekrar oyla?</a>